TARGET = retro-go-nes

DEBUG = 1
#OPT = -Og -ggdb
OPT = -O0 -ggdb3 -fsanitize=address

BUILD_DIR = build


C_SOURCES =  \
nes/main.c \
nes/nofrendo_linux.c \
odroid_input.c \
odroid_netplay.c \
odroid_overlay.c \
odroid_sdcard.c \
odroid_system.c \
odroid_display.c \
odroid_audio.c \
gw_lcd.c \
loaded_nes_rom.c \
crc32.c \
porting.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/bitmap.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/cpu/dis6502.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/cpu/nes6502.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map000.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map001.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map002.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map003.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map004.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map005.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map007.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map008.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map009.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map010.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map011.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map015.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map016.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map018.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map019.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map024.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map032.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map033.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map034.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map040.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map041.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map042.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map046.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map050.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map064.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map065.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map066.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map070.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map073.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map075.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map078.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map079.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map085.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map087.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map093.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map094.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map160.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map162.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map193.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map228.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map229.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/map231.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/mappers/mapvrc.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/nes/nes.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/nes/nes_apu.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/nes/nes_input.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/nes/nes_mem.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/nes/nes_mmc.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/nes/nes_ppu.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/nes/nes_rom.c \
../retro-go-stm32/nofrendo-go/components/nofrendo/nes/nes_state.c \


PREFIX = 

CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

C_DEFS =  \
-DIS_LITTLE_ENDIAN

C_INCLUDES =  \
-I. \
-I../retro-go-stm32/nofrendo-go/components/nofrendo/cpu \
-I../retro-go-stm32/nofrendo-go/components/nofrendo/mappers \
-I../retro-go-stm32/nofrendo-go/components/nofrendo/nes \
-I../retro-go-stm32/nofrendo-go/components/nofrendo \
-I../retro-go-stm32/components/odroid


ASFLAGS = $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS  = $(C_DEFS) $(C_INCLUDES) `sdl2-config --cflags` $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

#LIBS = -lm `sdl2-config --libs`
LIBS = -lasan -lm `sdl2-config --libs`
LDFLAGS = $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

all: $(BUILD_DIR)/$(TARGET).elf

OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))


$(BUILD_DIR)/%.o: %.c Makefile.nes | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile.nes
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR):
	mkdir $@

clean:
	-rm -fR $(BUILD_DIR)

-include $(wildcard $(BUILD_DIR)/*.d)
